[package]
name = "opsline"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive", "cargo"] }
git2 = { version = "0.21.0", default-features = false, features = ["vendored-libgit2"] }
kube = { version = "4.2.0", features = ["config"] }
libc = "0.2.189"
serde = { version = "1.0.229", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
ureq = { version = "3.4.0", features = ["json"] }
