use super::{BackgroundColor, ForegroundColor, Theme};

pub const DEFAULT: Theme = Theme {
    cwd_bg: BackgroundColor(241),
    cwd_fg: ForegroundColor(250),
    container_bg: BackgroundColor(55),
    container_fg: ForegroundColor(177),
    git_branch_bg: BackgroundColor(148),
    git_branch_fg: ForegroundColor(0),
    git_ahead_bg: BackgroundColor(240),
    git_ahead_fg: ForegroundColor(250),
    git_behind_bg: BackgroundColor(240),
    git_behind_fg: ForegroundColor(250),
    git_modified_bg: BackgroundColor(129),
    git_modified_fg: ForegroundColor(14),
    git_staged_bg: BackgroundColor(22),
    git_staged_fg: ForegroundColor(15),
    git_untracked_bg: BackgroundColor(52),
    git_untracked_fg: ForegroundColor(15),
    git_conflicted_bg: BackgroundColor(9),
    git_conflicted_fg: ForegroundColor(15),
    kube_context_bg: BackgroundColor(26),
    kube_context_fg: ForegroundColor(117),
    kube_namespace_bg: BackgroundColor(17),
    kube_namespace_fg: ForegroundColor(170),
    readonly_bg: BackgroundColor(124),
    readonly_fg: ForegroundColor(254),
    root_bg: BackgroundColor(236),
    root_fg: ForegroundColor(15),
    ssh_bg: BackgroundColor(166),
    ssh_fg: ForegroundColor(254),
};
