use super::{BackgroundColor, ForegroundColor, Theme};

pub const DEFAULT: Theme = Theme {
    cwd_bg: BackgroundColor::from_color_code(241),
    cwd_fg: ForegroundColor::from_color_code(250),
    container_bg: BackgroundColor::from_color_code(55),
    container_fg: ForegroundColor::from_color_code(177),
    git_branch_bg: BackgroundColor::from_color_code(148),
    git_branch_fg: ForegroundColor::from_color_code(0),
    git_ahead_bg: BackgroundColor::from_color_code(240),
    git_ahead_fg: ForegroundColor::from_color_code(250),
    git_behind_bg: BackgroundColor::from_color_code(240),
    git_behind_fg: ForegroundColor::from_color_code(250),
    git_modified_bg: BackgroundColor::from_color_code(129),
    git_modified_fg: ForegroundColor::from_color_code(14),
    git_staged_bg: BackgroundColor::from_color_code(22),
    git_staged_fg: ForegroundColor::from_color_code(15),
    git_untracked_bg: BackgroundColor::from_color_code(52),
    git_untracked_fg: ForegroundColor::from_color_code(15),
    git_conflicted_bg: BackgroundColor::from_color_code(9),
    git_conflicted_fg: ForegroundColor::from_color_code(15),
    kube_context_bg: BackgroundColor::from_color_code(26),
    kube_context_fg: ForegroundColor::from_color_code(117),
    kube_namespace_bg: BackgroundColor::from_color_code(17),
    kube_namespace_fg: ForegroundColor::from_color_code(170),
    readonly_bg: BackgroundColor::from_color_code(124),
    readonly_fg: ForegroundColor::from_color_code(254),
    root_bg: BackgroundColor::from_color_code(236),
    root_fg: ForegroundColor::from_color_code(15),
    ssh_bg: BackgroundColor::from_color_code(166),
    ssh_fg: ForegroundColor::from_color_code(254),
    terraform_bg: BackgroundColor::from_color_code(26),
    terraform_fg: ForegroundColor::from_color_code(15),
};
