use super::{BackgroundColor, ForegroundColor, Theme};

pub const DEFAULT: Theme = Theme {
    cwd_bg: BackgroundColor::colorless(),
    cwd_fg: ForegroundColor::from_color_code(250),
    container_bg: BackgroundColor::colorless(),
    container_fg: ForegroundColor::from_color_code(177),
    git_branch_bg: BackgroundColor::colorless(),
    git_branch_fg: ForegroundColor::from_color_code(15),
    git_ahead_bg: BackgroundColor::colorless(),
    git_ahead_fg: ForegroundColor::from_color_code(250),
    git_behind_bg: BackgroundColor::colorless(),
    git_behind_fg: ForegroundColor::from_color_code(250),
    git_modified_bg: BackgroundColor::colorless(),
    git_modified_fg: ForegroundColor::from_color_code(14),
    git_staged_bg: BackgroundColor::colorless(),
    git_staged_fg: ForegroundColor::from_color_code(15),
    git_untracked_bg: BackgroundColor::colorless(),
    git_untracked_fg: ForegroundColor::from_color_code(15),
    git_conflicted_bg: BackgroundColor::colorless(),
    git_conflicted_fg: ForegroundColor::from_color_code(15),
    kube_context_bg: BackgroundColor::colorless(),
    kube_context_fg: ForegroundColor::from_color_code(117),
    kube_namespace_bg: BackgroundColor::colorless(),
    kube_namespace_fg: ForegroundColor::from_color_code(170),
    readonly_bg: BackgroundColor::colorless(),
    readonly_fg: ForegroundColor::from_color_code(254),
    root_bg: BackgroundColor::colorless(),
    root_fg: ForegroundColor::from_color_code(15),
    ssh_bg: BackgroundColor::colorless(),
    ssh_fg: ForegroundColor::from_color_code(254),
    terraform_bg: BackgroundColor::colorless(),
    terraform_fg: ForegroundColor::from_color_code(15),
};
