use super::{BackgroundColor, ForegroundColor, Theme};

pub const GRUVBOX: Theme = Theme {
    cwd_bg: BackgroundColor(66),
    cwd_fg: ForegroundColor(250),
    container_bg: BackgroundColor(96),
    container_fg: ForegroundColor(229),
    git_branch_bg: BackgroundColor(100),
    git_branch_fg: ForegroundColor(237),
    git_ahead_bg: BackgroundColor(239),
    git_ahead_fg: ForegroundColor(248),
    git_behind_bg: BackgroundColor(239),
    git_behind_fg: ForegroundColor(248),
    git_modified_bg: BackgroundColor(166),
    git_modified_fg: ForegroundColor(229),
    git_staged_bg: BackgroundColor(106),
    git_staged_fg: ForegroundColor(229),
    git_untracked_bg: BackgroundColor(88),
    git_untracked_fg: ForegroundColor(229),
    git_conflicted_bg: BackgroundColor(124),
    git_conflicted_fg: ForegroundColor(229),
    kube_context_bg: BackgroundColor(235),
    kube_context_fg: ForegroundColor(229),
    kube_namespace_bg: BackgroundColor(236),
    kube_namespace_fg: ForegroundColor(229),
    readonly_bg: BackgroundColor(167),
    readonly_fg: ForegroundColor(229),
    root_bg: BackgroundColor(237),
    root_fg: ForegroundColor(246),
    ssh_bg: BackgroundColor(96),
    ssh_fg: ForegroundColor(229),
    terraform_bg: BackgroundColor(129),
    terraform_fg: ForegroundColor(15),
};
