use super::{BackgroundColor, ForegroundColor, Theme};

pub const GRUVBOX: Theme = Theme {
    cwd_bg: BackgroundColor::from_color_code(66),
    cwd_fg: ForegroundColor::from_color_code(250),
    container_bg: BackgroundColor::from_color_code(96),
    container_fg: ForegroundColor::from_color_code(229),
    git_branch_bg: BackgroundColor::from_color_code(100),
    git_branch_fg: ForegroundColor::from_color_code(237),
    git_ahead_bg: BackgroundColor::from_color_code(239),
    git_ahead_fg: ForegroundColor::from_color_code(248),
    git_behind_bg: BackgroundColor::from_color_code(239),
    git_behind_fg: ForegroundColor::from_color_code(248),
    git_modified_bg: BackgroundColor::from_color_code(166),
    git_modified_fg: ForegroundColor::from_color_code(229),
    git_staged_bg: BackgroundColor::from_color_code(106),
    git_staged_fg: ForegroundColor::from_color_code(229),
    git_untracked_bg: BackgroundColor::from_color_code(88),
    git_untracked_fg: ForegroundColor::from_color_code(229),
    git_conflicted_bg: BackgroundColor::from_color_code(124),
    git_conflicted_fg: ForegroundColor::from_color_code(229),
    kube_context_bg: BackgroundColor::from_color_code(235),
    kube_context_fg: ForegroundColor::from_color_code(229),
    kube_namespace_bg: BackgroundColor::from_color_code(236),
    kube_namespace_fg: ForegroundColor::from_color_code(229),
    readonly_bg: BackgroundColor::from_color_code(167),
    readonly_fg: ForegroundColor::from_color_code(229),
    root_bg: BackgroundColor::from_color_code(237),
    root_fg: ForegroundColor::from_color_code(246),
    ssh_bg: BackgroundColor::from_color_code(96),
    ssh_fg: ForegroundColor::from_color_code(229),
    terraform_bg: BackgroundColor::from_color_code(129),
    terraform_fg: ForegroundColor::from_color_code(15),
};
