use super::{BackgroundColor, ForegroundColor, Theme};

pub const GRUVBOX: Theme = Theme {
    cwd_bg: BackgroundColor::colorless(),
    cwd_fg: ForegroundColor::from_color_code(223),
    container_bg: BackgroundColor::colorless(),
    container_fg: ForegroundColor::from_color_code(208),
    git_branch_bg: BackgroundColor::colorless(),
    git_branch_fg: ForegroundColor::from_color_code(142),
    git_ahead_bg: BackgroundColor::colorless(),
    git_ahead_fg: ForegroundColor::from_color_code(108),
    git_behind_bg: BackgroundColor::colorless(),
    git_behind_fg: ForegroundColor::from_color_code(167),
    git_modified_bg: BackgroundColor::colorless(),
    git_modified_fg: ForegroundColor::from_color_code(214),
    git_staged_bg: BackgroundColor::colorless(),
    git_staged_fg: ForegroundColor::from_color_code(142),
    git_untracked_bg: BackgroundColor::colorless(),
    git_untracked_fg: ForegroundColor::from_color_code(175),
    git_conflicted_bg: BackgroundColor::colorless(),
    git_conflicted_fg: ForegroundColor::from_color_code(167),
    kube_context_bg: BackgroundColor::colorless(),
    kube_context_fg: ForegroundColor::from_color_code(109),
    kube_namespace_bg: BackgroundColor::colorless(),
    kube_namespace_fg: ForegroundColor::from_color_code(175),
    readonly_bg: BackgroundColor::colorless(),
    readonly_fg: ForegroundColor::from_color_code(167),
    root_bg: BackgroundColor::colorless(),
    root_fg: ForegroundColor::from_color_code(223),
    ssh_bg: BackgroundColor::colorless(),
    ssh_fg: ForegroundColor::from_color_code(208),
    terraform_bg: BackgroundColor::colorless(),
    terraform_fg: ForegroundColor::from_color_code(175),
};
